version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "1952:1952"
    volumes:
      - .:/usr/app
  postgres:
    container_name: geoara
    image: postgres
    environment:
      POSTGRES_USER: geoara
      POSTGRES_PASSWORD: login123
      POSTGRES_DB: geoara
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/migrations/query.sql:/docker-entrypoint-initdb.d/query.sql
    ports:
      - "5432:5432"