version: "3"

services:
  api:
    image: joaovitormlbr/geoara-devops:${DOCKER_IMAGE_TAG}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - app_network
    env_file:
      - .env

  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: geoara
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: geoara
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/migrations/query.sql:/docker-entrypoint-initdb.d/query.sql
    ports:
      - "5433:5432"
    networks:
      - app_network
    healthcheck:
      # Ajustado para usar pg_isready, uma forma mais robusta de checar a saúde do PostgreSQL
      test: ["CMD-SHELL", "pg_isready -h localhost -U geoara -d geoara"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  app_network:
    driver: bridge
