# @format

version: "3"

services:
  api:
    image: joaovitormlbr/geoara-devops:${DOCKER_IMAGE_TAG}
    depends_on:
      db:
        condition: service_healthy
    ports: 
      - "3000:3000"
    networks:
      - app_network
   
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/migrations/query.sql:/docker-entrypoint-initdb.d/query.sql
    ports:
      - "5433:5432"
    networks:
      - app_network 
    healthcheck:
      test: ["CMD-SHELL", "psql -h localhost -U geoara -d geoara"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
networks:
  app_network:
    driver: bridge
