name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ${{ matrix.os }}
    outputs:
      docker_tag: ${{ steps.generate_tag.outputs.sha }}

    strategy:
      matrix:
        node-version: [22]
        os: [ubuntu-latest]
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install

      # - name: Running Tests
      #   run: npm test

      - name: Generate Tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker Image
        run: docker build -t joaovitormlbr/geoara-devops:${{ steps.generate_tag.outputs.sha }} .

      - name: Push Docker Image to DockerHub
        run: docker push joaovitormlbr/geoara-devops:${{ steps.generate_tag.outputs.sha }}

  deploy:
    name: Deploy on Digital Ocean
    runs-on: ubuntu-latest
    needs: build  # Garantindo que o deploy depende da conclusão do job de build

    steps:
      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          echo "StrictHostKeyChecking no" >> ~/.ssh/config  # Desativa a verificação de chave

      - name: Debug known_hosts
        run: cat ~/.ssh/known_hosts

      - name: Deploy on Digital Ocean via ssh
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # Extrair o tag da construção
            TAG=${{ needs.build.outputs.docker_tag }}
          
            # Verificar se o .env já existe, caso contrário, criar
            if [ ! -f .env ]; then
              echo ".env não encontrado! Criando um novo arquivo."
              touch .env
            fi

            # Adicionar/Atualizar DOCKER_IMAGE_TAG no .env
            echo "DOCKER_IMAGE_TAG=$TAG" >> .env
          
            # Verificar se o arquivo .env-ps já existe no servidor
            if ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password ${{ secrets.USER }}@${{ secrets.HOST }} "[ -f ~/.env-ps ]"; then
              echo "O arquivo .env-ps já existe no servidor. Fazendo backup..."
              ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password ${{ secrets.USER }}@${{ secrets.HOST }} "cp ~/.env-ps ~/.env-ps.backup"
            fi

            # Copiar o arquivo .env-ps para o servidor (com depuração)
            scp -v -o StrictHostKeyChecking=no -o PreferredAuthentications=password ./.env-ps ${{ secrets.USER }}@${{ secrets.HOST }}:~/.env-ps

            # Copiar o arquivo docker-compose.yml para o servidor
            scp -v -o StrictHostKeyChecking=no -o PreferredAuthentications=password ./docker-compose.yml ${{ secrets.USER }}@${{ secrets.HOST }}:~/docker-compose.yml
        
            # Login no Docker
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            
            # Parar os containers
            CONTAINERS=$(docker ps -q)
            if [ -n "$CONTAINERS" ]; then
              docker stop $CONTAINERS
            else
              echo "Nenhum container em execução"
            fi
        
            # Remover containers antigos
            CONTAINERS=$(docker ps -a -q)
            if [ -n "$CONTAINERS" ]; then
              docker rm $CONTAINERS
            else
              echo "Nenhum container para remover"
            fi
        
            # Navegar para o diretório do projeto e subir o container
            ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password ${{ secrets.USER }}@${{ secrets.HOST }} "cd ~ && docker-compose up -d --build"